<?xml version="1.0" encoding="UTF-8" ?>
<testsuites disabled="0" errors="0" failures="1" tests="1" time="0.111">
 <testsuite name="Login Module" timestamp="2020-05-09T11:55:52" hostname="localhost" time="0.111" errors="0" tests="1" skipped="0" disabled="0" failures="1">
  <testcase classname="Login Module" name="Enter no inputs" time="0.045">
   <failure type="exception" message="Failed: ENOENT: no such file or directory, open &apos;testdata.xlsx&apos;"><![CDATA[Error: ENOENT: no such file or directory, open 'testdata.xlsx'
    at Object.openSync (fs.js:457:3)
    at Object.readFileSync (fs.js:359:35)
    at read_binary (D:\AngularProject\Angular_Protactor\NI2_Health\node_modules\xlsx\xlsx.js:2631:44)
    at readSync (D:\AngularProject\Angular_Protactor\NI2_Health\node_modules\xlsx\xlsx.js:20775:69)
    at Object.readFileSync (D:\AngularProject\Angular_Protactor\NI2_Health\node_modules\xlsx\xlsx.js:20803:9)
    at Object.methods.getWorkSheet (D:\AngularProject\Angular_Protactor\NI2_Health\excelutils\readfile.js:16:24)
    at UserContext.<anonymous> (D:\AngularProject\Angular_Protactor\NI2_Health\tests\example_spec.js:7:31)
    at C:\Users\LATITUDE\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\LATITUDE\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\LATITUDE\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
From: Task: Run it("Enter no inputs") in control flow
    at UserContext.<anonymous> (C:\Users\LATITUDE\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\LATITUDE\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\LATITUDE\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at QueueRunner.execute (C:\Users\LATITUDE\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4199:10)
    at Spec.queueRunnerFactory (C:\Users\LATITUDE\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:909:35)
    at Spec.execute (C:\Users\LATITUDE\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:526:10)
    at UserContext.fn (C:\Users\LATITUDE\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:5340:37)
    at attempt (C:\Users\LATITUDE\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\LATITUDE\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at QueueRunner.execute (C:\Users\LATITUDE\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4199:10)
From asynchronous test: 
Error
    at Suite.<anonymous> (D:\AngularProject\Angular_Protactor\NI2_Health\tests\example_spec.js:5:2)
    at addSpecsToSuite (C:\Users\LATITUDE\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\LATITUDE\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\LATITUDE\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.<anonymous> (D:\AngularProject\Angular_Protactor\NI2_Health\tests\example_spec.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)]]>
   </failure>
  </testcase>
 </testsuite>
</testsuites>